[package]
name = "topos-tce"
version = "0.1.0"
edition = "2021"
license = "MIT"

# our main binary
[[bin]]
name = "topos-tce-app"
path = "src/tce_node_app.rs"

[dependencies]
# external dependencies
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "3.0.10", features = ["derive", "env"] }
libp2p = { version = "0.46", features = ["tcp-tokio"] }
lazy_static = "1.4"
log = "0.4.14"
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
pretty_env_logger = "0.4.0"
tokio = { version = "1.20.0", features = [
    "io-util",
    "io-std",
    "macros",
    "rt",
    "rt-multi-thread",
    "fs",
    "time",
    "sync",
] }

# tce dependencies
tce_api = { package = "topos-tce-api", path = "./crates/topos-tce-api" }
tce_store = { package = "topos-tce-store", path = "./crates/topos-tce-store" }
tce_telemetry = { package = "topos-tce-telemetry", path = "./crates/topos-tce-telemetry" }
topos-tce-broadcast = { path = "./crates/topos-tce-broadcast" }
tce_transport = { package = "topos-tce-transport", path = "./crates/topos-tce-transport" }

topos-p2p = { path = "./crates/topos-p2p" }
topos-addr = { git = "https://github.com/Toposware/topos-p2p", branch = "main", version = "0.1.0", package = "topos-addr"}

tracing = { version = "*", default-features = false, features = ["log"]}
tracing-log = { version = "*", features = ['env_logger'] }
futures = "*"

[dev-dependencies]
async-trait = "0.1"
cucumber = "0.13.0"
hyper = { version = "0.14", features = ["full"] }
rand_distr = "0.4.1"
rand_core = "0.6.0"
rand = "0.8.5"
env_logger = "*"
test-log = { version = "0.2", features = ["log"] }

[[test]]
name = "example" # this should be the same as the filename of your test target
harness = false  # allows Cucumber to print output instead of libtest

[workspace]
members = [
    "crates/*"
]
