[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"

[lib]
path = 'src/lib.rs'

[dependencies]
serde.workspace = true

topos-core = { workspace = true, features = ["uci"] }

topos-p2p = { path = "../topos-p2p/"}

clap = { version = "4.0.27", features = ["derive", "env"] }
