[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"

[lib]
path = 'src/lib.rs'

[dependencies]
clap.workspace = true
serde = { workspace = true, features = ["rc"] }
tracing.workspace = true
secp256k1.workspace = true
hex.workspace = true
topos-core = { workspace = true, features = ["uci"] }
topos-p2p = { path = "../topos-p2p/"}

