[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"

[lib]
path = 'src/lib.rs'

[dependencies]
serde.workspace = true

topos-core = { workspace = true, features = ["uci"] }

clap = { version = "3.0.10", features = ["derive", "env"] }
