[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = 'src/lib.rs'

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
clap = { version = "3.0.10", features = ["derive", "env"] }

topos-core = { git = "https://github.com/toposware/topos-core", branch = "main", features = ["uci"], version = "0.1.0" }

