[package]
name = "topos-sequencer-subnet-client"
version = "0.1.0"
edition = "2021"

[dependencies]
topos-sequencer-types = { package = "topos-sequencer-types", path = "../topos-sequencer-types" }

thiserror.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
hex.workspace = true
web3.workspace = true

jsonrpsee-types = "0.14.0"
ethereum-tx-sign = "6.0.0"
keccak-hash = "0.9"
secp256k1 = "0.24"
tiny-keccak = "1.2"

