[package]
name = "topos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.27", features = ["derive", "env"] }

tokio = { workspace = true, features = ["full"] }
topos-core = { workspace = true, features = ["api"] }
uuid = { version = "1.1.2", features = ["v4"] }

topos-tce = { path = "../topos-tce/" }
topos-p2p = { path = "../topos-p2p" }
topos-tce-transport = { path = "../topos-tce-transport" }
tower = "0.4.13"
tonic.workspace = true
futures.workspace = true
serde.workspace = true
serde_json = "1.0.89"

[dev-dependencies]
assert_cmd = "2.0.6"
insta = "1.21"
