[package]
name = "topos"
version = "0.1.0"
edition = "2021"

[dependencies]
topos-tce = { path = "../topos-tce/", optional = true }
topos-p2p = { path = "../topos-p2p" }
topos-tce-transport = { path = "../topos-tce-transport", optional = true }
topos-sequencer = { path = "../topos-sequencer", optional = true }
topos-core = { workspace = true, features = ["api"] }
topos-certificate-spammer = { path = "../topos-certificate-spammer", optional = true }

async-stream.workspace = true
async-trait.workspace = true
clap.workspace = true
futures.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tower.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-log = { version = "0.1.3", features = ["env_logger"] }
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "ansi", "fmt"] }
uuid.workspace = true
rand.workspace = true

[dev-dependencies]
topos-tce-broadcast = { path = "../topos-tce-broadcast" }
topos-tce-transport = { path = "../topos-tce-transport" }
topos-tce-synchronizer = { path = "../topos-tce-synchronizer" }
topos-tce-gatekeeper = { path = "../topos-tce-gatekeeper" }
topos-tce-api = {path = "../topos-tce-api"}
topos-tce-storage = { path = "../topos-tce-storage" }
topos-test-sdk = { path = "../topos-test-sdk", features = ["tce"] }
serde.workspace = true
serde_json.workspace = true
test-log.workspace = true
env_logger.workspace = true
rand.workspace = true
async-stream.workspace = true
futures.workspace = true
libp2p = { workspace = true, features = ["identify"] }
assert_cmd = "2.0.6"
insta = { version = "1.21", features = ["json", "redactions"] }

[features]
default = ["tce", "sequencer", "network"]
tce = ["topos-tce", "topos-tce-transport"]
sequencer = ["topos-sequencer"]
network = ["topos-certificate-spammer"]

tce-direct = ["tce", "topos-tce-broadcast/direct"]
