[package]
name = "topos-sequencer-types"
version = "0.1.0"
edition = "2021"

[dependencies]
topos-core = { workspace = true, features = ["uci"] }

ethereum-types.workspace = true
serde = { workspace = true, features = ["derive"] }
