[package]
name = "topos-sequencer-subnet-runtime-proxy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "create-keystore"
path = "src/keystore.rs"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
byteorder = "1.4.3"
log = "0.4.14"
tokio = { version = "1.15.0", features = [
    "io-util",
    "io-std",
    "macros",
    "rt",
    "rt-multi-thread",
    "fs",
    "time",
    "sync",
] }
rand_distr = "0.4.1"
rand_core = "0.6.0"
rand = "0.8.5"
thiserror = "1.0"
clap = { version = "3.0.10", features = ["derive", "env"] }
hex = "0.4.3"
eth-keystore = "0.5.0"
ethereum-tx-sign = "6.0"

topos-sequencer-types = { package = "topos-sequencer-types", path = "../topos-sequencer-types" }
topos-sequencer-subxt-client = { package = "topos-sequencer-subxt-client", path = "../topos-sequencer-subxt-client" }
topos-core = { workspace = true, features = ["uci"] }

[dev-dependencies]
pretty_env_logger = "0.4.0"
rstest = "0.15"
serial_test = "0.9"
dockertest = "0.3.1"
web3 = { version = "0.18.0", features = ["signing"]}
serde_json = "1.0.85"
secp256k1 = { version = "0.21", features = ["recovery"]}
tiny-keccak = "1.2"
