name: Contracts - Docker build and push

on:
  push:
    branches: feat/TP-888
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/contract-docker-utils.yml
  e2e:
    needs: docker
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest-16-core
    steps:
      - name: Set environment
        run: |
          # It's fine to assume a single tag. Our tagging strategy follows a 1:1 mapping of image:tag
          tags=${{ needs.docker.outputs.tags }}
          echo "docker_tag=${tags#*:}" >> $GITHUB_ENV
        shell: bash

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-protocol
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: frontend:erc20-messaging.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "topos-smart-contracts-docker-tag": "${{ env.docker_tag }}" }'
