name: Coverage

on:
  push:
    branches: [main]
    paths: crates/**
  pull_request:
    branches: [main]
    paths: crates/**
  workflow_dispatch:

jobs:
  codecov:
    name: Code coverage
    runs-on: ubuntu-latest-16-cores

    steps:
      - uses: actions/checkout@v3

      - run: |
          git config --global url."https://${{ secrets.ROBOT_TOPOSWARE_PRIV_REPOS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: 0.24.0
      - run: cargo tarpaulin --engine llvm --workspace --all-features --release --exclude topos-sequencer-subnet-runtime-proxy

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
