name: Docker build and push

on:
  push:
    branches: [main, debug/**]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit

  integration-erc20-e2e:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Set environment
        run: |
          # It's fine to assume a single tag. Our tagging strategy follows a 1:1 mapping of image:tag
          tags=${{ needs.docker.outputs.tags }}
          echo "docker_tag=${tags#*:}" >> $GITHUB_ENV
        shell: bash

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-protocol
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: topos:integration-tests.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "topos-docker-tag": "${{ env.docker_tag }}", "topos-smart-contracts-docker-tag": "3.2.0" }'

  frontend-erc20-e2e:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Set environment
        run: |
          # It's fine to assume a single tag. Our tagging strategy follows a 1:1 mapping of image:tag
          tags=${{ needs.docker.outputs.tags }}
          echo "docker_tag=${tags#*:}" >> $GITHUB_ENV
        shell: bash

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-protocol
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: frontend:erc20-messaging.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "topos-docker-tag": "${{ env.docker_tag }}", "topos-smart-contracts-docker-tag": "3.2.0"}'
